# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Felipe Quadros (Blog do Perera)
email: felipepqm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um Desenvolvedor com o intuito de aprender e repassar o conteúdo aprendido estudando desenvolvimento web. :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://felipequadros.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  FpereraMaia

# Build settings
markdown: kramdown
timezone: America/Sao_Paulo

permalink: pretty
